AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AppInstanceTypeParameter:
    Type: String
    Default: t2.micro
  InfraInstanceTypeParameter:
    Type: String
    Default: t2.medium
  AMI:
    Type: String
    Default: ami-0b4577d77dac11b84 
Resources:
  IfraInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "prequel infra SG"
      GroupDescription: "SG for the prequel infrastructure"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 54.160.23.189/32
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 18.208.32.56/32
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 3.229.31.196/32
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 44.210.38.194/32
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0 
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8085'
          ToPort: '8085'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8000'
          ToPort: '8000'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8088'
          ToPort: '8088'
          CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: course
          Value: IEA
        -
          Key: cohort
          Value: 8
  AppInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "prequel app SG"
      GroupDescription: "SG for the prequel infrastructure"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0 
        - IpProtocol: tcp
          FromPort: '8088'
          ToPort: '8088'
          CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: course
          Value: IEA
        -
          Key: cohort
          Value: 8
  PrequelInfrastructure:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType:
        Ref: InfraInstanceTypeParameter
      KeyName: PrequelKey
      SecurityGroupIds:
        - Ref: IfraInstanceSG
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 250
      Tags:
        -
          Key: course
          Value: IEA
        -
          Key: cohort
          Value: 8
        -
          Key: name
          Value: PrequelInfrastructure
  PrequelStaging:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType:
        Ref: AppInstanceTypeParameter
      KeyName: PrequelKey
      SecurityGroupIds:
        - Ref: AppInstanceSG
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 250
      Tags:
        -
          Key: course
          Value: IEA
        -
          Key: cohort
          Value: 8
        -
          Key: name
          Value: PrequelStaging
  PrequelProd:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType:
        Ref: AppInstanceTypeParameter
      KeyName: PrequelKey
      SecurityGroupIds:
        - Ref: AppInstanceSG
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 250
      Tags:
        -
          Key: course
          Value: IEA
        -
          Key: cohort
          Value: 8
        -
          Key: name
          Value: PrequelProd
Outputs:
  InfraPublicIp:
    Value:
      Fn::GetAtt:
        - PrequelInfrastructure
        - PublicIp
    Description: Server's PublicIp Address
  StagingPublicIp:
    Value:
      Fn::GetAtt:
        - PrequelStaging
        - PublicIp
    Description: Server's PublicIp Address
  ProdPublicIp:
    Value:
      Fn::GetAtt:
        - PrequelProd
        - PublicIp
    Description: Server's PublicIp Address