---
- hosts: all
  become: true
  vars:
    container_count: 1
    default_container_name: docker
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

    - name: Build Docker volume and image creation
      hosts: infra
      tasks:
      - name: Create Docker volume
        community.docker.docker_volume:
          name: bambooVolume
    - debug: msg= "{{ Docker Volume was successfully created. }}"

    - name: Pull Docker image
      tasks: 
        - name: Docker image
          community.docker.docker_image:
            name: jrrickerson/capstone-bamboo
            source: pull
            pull:
              path: "{{ /srv/bamboodockerimage }}"
              platform: amd64
    - debug: msg= "{{ Docker image was successfully pulled. }}"

    - name: Docker image creation
      community.docker.docker_container:
        name: bamboo
        build:
          pull: yes
          path: "{{/srv/bamboodockerimage/jrrickerson/}}"
        state: present
        exposed_ports:
          - 54663
          - 8085
        volumes:
          - /var/lib/docker/volume/
    - debug: msg= "{{ Docker image was successfully created. }}"          
