---
- hosts: all
  become: true
  vars:
    container_count: 1
    default_container_name: docker
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

- hosts: infra
  become: true
  tasks:
    - name: Build Docker volume and image creation
      community.docker.docker_volume:
        name: bambooVolume
    - debug: 
        msg: "Docker Volume was successfully created."

#    - name: Pull Docker image
#      community.docker.docker_image:
#        name: jrrickerson/capstone-bamboo
#        source: pull
#        pull:
#          path: "{{ /srv/bamboodockerimage }}"
#          platform: amd64
#    - debug: msg= "{{ Docker image was successfully pulled. }}"

    - name: Docker image creation
      community.docker.docker_container:
        name: bamboo
        image: labadieb/capstone-bamboo:v2
        state: started
        published_ports:
          - 54663:54663
          - 8085:8085
        volumes:
          - "bambooVolume:/var/atlassian/application-data/bamboo"  
    - debug: 
        msg: "Docker image was successfully created."   

- hosts: app
  become: true
  tasks:
    - name: copy docker compose file
      ansible.builtin.copy:
        src: ../wordpress/docker-compose.yaml
        dest: /opt
        owner: root
        mode: u+rw,g-wx,o-rwx
        
    - name: WordPress Docker Compose Install
      community.docker.docker_compose:
        project_src: /opt
        files:
        - docker-compose.yaml

