- hosts: app_group
  become: true
  tasks:
    - name: copy docker compose file
      ansible.builtin.copy:
        src: ../wordpress/docker-compose.yaml
        dest: /opt
        owner: root
        mode: u+rw,g-wx,o-rwx
        
    - name: Install required system packages
      apt:
        pkg:
          - python-pip
          - python-setuptools

        state: latest
        update_cache: yes

    - name: Install python setuptools_rust
      pip:
        name: setuptools_rust
        
    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install Docker-Compose Module for Python
      pip:
        name: docker-compose
    
    - name: WordPress Docker Compose Install
      community.docker.docker_compose:
        project_src: /opt
        files:
        - docker-compose.yaml

