---
- hosts: app_group
  become: true
  gather_facts: false
  tasks:       
    - name: Install required system packages
      apt:
        pkg:
          - python3-pip
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Install pip
      pip:
        name: pip
        state: latest
 
    - name: Install cryptography
      pip:
        name: cryptography<37.0.0
        state: present
        
    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install Docker-Compose Module for Python
      pip:
        name: docker-compose
        
- hosts: all
  become: true
  vars:
    container_count: 1
    default_container_name: docker

  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

- hosts: infra
  become: true
  tasks:
    - name: ssh file permission change
      ansible.builtin.file:
        path: /home/ubuntu/.ssh/PrequelKey.pem
        owner: 2005
        group: 2005
        mode: g-rx,o-rx
    - name: Build Docker volume
      community.docker.docker_volume:
        name: bambooVolume
    - debug: 
        msg: "Docker Volume was successfully created."

#    - name: Pull Docker image
#      community.docker.docker_image:
#        name: jrrickerson/capstone-bamboo
#        source: pull
#        pull:
#          path: "{{ /srv/bamboodockerimage }}"
#          platform: amd64
#    - debug: msg= "{{ Docker image was successfully pulled. }}"

    - name: Docker image creation
      community.docker.docker_container:
        name: bamboo
        groups: docker
        image: labadieb/capstone-bamboo:v2
        state: started
        published_ports:
          - 54663:54663
          - 8085:8085
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/ubuntu/.ssh:/var/atlassian/application-data/bamboo/.ssh/
          - "bambooVolume:/var/atlassian/application-data/bamboo"             
    - debug: 
        msg: "Docker image was successfully created."   
        