---
- hosts: all
  become: true
  vars:
    container_count: 1
    default_container_name: docker
    default_container_image: ubuntu
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

- hosts: infra
  become: true
  tasks:
    - name: ssh file permission change
      ansible.builtin.file:
        path: /home/ubuntu/.ssh/PrequelKey.pem
        owner: 2005
        group: 2005
        mode: g-rx,o-rx
    - name: Build Docker volume and image creation
      community.docker.docker_volume:
        name: bambooVolume
    - debug: 
        msg: "Docker Volume was successfully created."

#    - name: Pull Docker image
#      community.docker.docker_image:
#        name: jrrickerson/capstone-bamboo
#        source: pull
#        pull:
#          path: "{{ /srv/bamboodockerimage }}"
#          platform: amd64
#    - debug: msg= "{{ Docker image was successfully pulled. }}"

    - name: Docker image creation
      community.docker.docker_container:
        name: bamboo
        image: labadieb/capstone-bamboo:v2
        state: started
        published_ports:
          - 54663:54663
          - 8085:8085
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/ubuntu/.ssh:/var/atlassian/application-data/bamboo/.ssh/
          - "bambooVolume:/var/atlassian/application-data/bamboo"             
    - debug: 
        msg: "Docker image was successfully created."   
        