---
version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     logging:
       driver: "splunk"
       options:
        splunk-token: 93c7a156-e460-4578-9b8d-8c189666ec92
        splunk-url: https://3.16.30.232:8088
        splunk-insecureskipverify: "true"
     volumes:
      - wp-content:/var/www/html/
     ports:
       - "8088:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_CONFIG_EXTRA: define( 'WP_ENVIRONMENT_TYPE', 'local' );
volumes:
    db_data: {}
    wp-content: {}
